import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import {
  IoLogoInstagram as InstramIcon,
  IoLogoTwitter as TwitterIcon,
  IoLogoFacebook as FacebookIcon,
  IoLogoYoutube as YouTubeIcon
} from "react-icons/io";
import AuthPopup from "@/components/others/auth-popup";
import MenuDrawer from "@/components/others/menu-drawer";

import PublicNavbar from "@/components/others/public-navbar";
import PublicFooter from "@/components/others/public-footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative min-h-screen`}>
        <PublicNavbar />
        {children}
        <PublicFooter />
      </body>
    </html>
  );
}
